version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: always
    ports:
      - "2181:2181"
    # Mac M1 chip 사용 시 아래 platform 추가
    platform: linux/amd64

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    restart: always
    depends_on:
      - zookeeper
    links:
      - zookeeper:zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /kafka/logs
      KAFKA_BROKER_ID: 1
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_ALLOW_AUTO_CREATE_TOPICS: 'false'
      KAFKA_offsets_topic_relication_factor: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    restart: always
    ports:
      - "9001:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka-1:9092
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181

#  kafka-2:
#    image: wurstmeister/kafka
#    container_name: kafka-2
#    restart: always
#    depends_on:
#      - zookeeper
#    links:
#      - zookeeper:zookeeper
#    ports:
#      - "19092:19092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:19092
#      KAFKA_ADVERTISED_PORT: 19092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LOG_DIRS: /kafka/logs
#      KAFKA_BROKER_ID: 2
#      KAFKA_DELETE_TOPIC_ENABLE: 'true'
#      KAFKA_ALLOW_AUTO_CREATE_TOPICS: 'false'
#      KAFKA_offsets_topic_relication_factor: 1
#
#  kafka-3:
#    image: wurstmeister/kafka
#    container_name: kafka-3
#    restart: always
#    depends_on:
#      - zookeeper
#    links:
#      - zookeeper:zookeeper
#    ports:
#      - "29092:29092"
#    environment:
#      KAFKA_ADVERTISED_HOST_NAME: localhost
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
#      KAFKA_ADVERTISED_PORT: 29092
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_LOG_DIRS: /kafka/logs
#      KAFKA_BROKER_ID: 200
#      KAFKA_DELETE_TOPIC_ENABLE: 'true'
#      KAFKA_ALLOW_AUTO_CREATE_TOPICS: 'false'
#      KAFKA_offsets_topic_relication_factor: 1